apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aksdekratest-8e72"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aksdekratest-8e72"
  template:
    metadata:
      labels:
        app: "aksdekratest-8e72"
    spec:
      containers:
        - name: "aksdekratest-8e72"
          image: "akstestnewprasad.azurecr.io/aksdekratest"
          ports:
          - containerPort: 8085