apiVersion: v1
kind: Service
metadata:
    name: "aksdekratest-8e72"
    labels:
        app: "aksdekratest-8e72"
spec:
    type: LoadBalancer
    ports:
    - port: 8085
      targetPort: 8085
      protocol: TCP
      name: http
    selector:
        app: "aksdekratest-8e72"